trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  jobs:
    - job: Copyjob
      steps:
        - bash: ls -R $(Build.ArtifactStagingDirectory)
        - task: CopyFiles@2
          inputs:
            SourceFolder: '$(System.DefaultWorkingDirectory)'
            Contents: |
              **/*.yml
              **/*.java
            TargetFolder: '$(Build.ArtifactStagingDirectory)'
        - bash: ls -R $(Build.ArtifactStagingDirectory)

- stage: Deploy
  jobs:  # <-- this was incorrectly indented before
    - job: Deployjob
      steps:
        - bash: ls -R $(Build.ArtifactStagingDirectory)
        - task: PublishBuildArtifacts@1
          inputs:
            PathtoPublish: '$(Build.ArtifactStagingDirectory)'
            ArtifactName: 'drop'
            publishLocation: 'Container'

